import { db } from '@/lib/db'
import { campaigns, agentLogs, apifyJobs, posts } from '@/lib/db/schema'
import { eq } from 'drizzle-orm'
import { runPlanner } from './planner'
import { runWriter } from './writer'
import { runReviewer } from './reviewer'

async function log(campaignId: string, role: typeof agentLogs.$inferInsert['role'], status: typeof agentLogs.$inferInsert['status'], message: string, output?: string) {
  await db.insert(agentLogs).values({ id: crypto.randomUUID(), campaignId, role, status, message, output })
}

async function updateCampaign(id: string, patch: Partial<typeof campaigns.$inferInsert>) {
  await db.update(campaigns).set(patch).where(eq(campaigns.id, id))
}

export async function runAgentPipeline(campaignId: string): Promise<{ postsCreated: number }> {
  const [campaign] = await db.select().from(campaigns).where(eq(campaigns.id, campaignId))
  if (!campaign) throw new Error('Campaign not found')

  // 1. Gather Apify research results
  let researchSummary: string | undefined
  const completedJobs = await db.select().from(apifyJobs).where(eq(apifyJobs.campaignId, campaignId))
  if (completedJobs.some(j => j.result)) {
    researchSummary = completedJobs
      .filter(j => j.result)
      .map(j => `[${j.type}] Query: ${j.query}\nResult: ${j.result}`)
      .join('\n\n')
  }

  // 2. Planner
  await updateCampaign(campaignId, { currentStep: 'planner', progress: 10 })
  await log(campaignId, 'planner', 'running', 'Analyzing campaign brief and building content strategy…')

  const strategy = await runPlanner({
    campaignName: campaign.name,
    description: campaign.description,
    platforms: campaign.platforms,
    contentPillars: campaign.contentPillars,
    researchResults: researchSummary,
  })

  await log(campaignId, 'planner', 'done',
    `Content strategy created: ${strategy.total_posts} posts over ${strategy.duration_days} days.`,
    strategy.summary
  )
  await updateCampaign(campaignId, { currentStep: 'writer', progress: 35 })

  // 3. Writer
  await log(campaignId, 'writer', 'running', `Writing ${strategy.total_posts} post drafts…`)

  const drafts = await runWriter({
    strategy,
    campaignName: campaign.name,
    campaignDescription: campaign.description,
  })

  await log(campaignId, 'writer', 'done',
    `${drafts.length} post drafts written across ${[...new Set(drafts.map(d => d.platform))].join(', ')}.`
  )
  await updateCampaign(campaignId, { currentStep: 'reviewer', progress: 60 })

  // 4. Reviewer
  await log(campaignId, 'reviewer', 'running', 'Reviewing posts for brand voice and quality…')

  const reviewResult = await runReviewer({ drafts, campaignName: campaign.name })

  await log(campaignId, 'reviewer', 'done',
    `Review complete: ${reviewResult.approved_count} approved, ${reviewResult.revised_count} revised.`,
    reviewResult.overall_feedback
  )
  await updateCampaign(campaignId, { currentStep: 'publisher', progress: 80 })

  // 5. Save posts — fall back to raw drafts if reviewer returned nothing
  const sourcePosts = reviewResult.posts.length > 0 ? reviewResult.posts : drafts
  const finalPosts = sourcePosts.map(p => ({
    platform: p.platform,
    title: p.title,
    content: String(('approved' in p && !p.approved && 'revision' in p) ? (p.revision ?? p.content) : p.content),
    hashtags: p.hashtags,
    call_to_action: p.call_to_action,
    scheduled_day: p.scheduled_day,
  }))

  const today = new Date()
  const postRecords = finalPosts.map(p => {
    const scheduledDate = new Date(today)
    scheduledDate.setDate(today.getDate() + (p.scheduled_day - 1))
    scheduledDate.setHours(9, 0, 0, 0)
    return {
      id: crypto.randomUUID(),
      campaignId,
      title: p.title,
      content: p.content,
      platform: p.platform,
      status: 'scheduled' as const,
      scheduledAt: scheduledDate,
    }
  })

  if (postRecords.length === 0) throw new Error('No posts generated by the pipeline')
  await db.insert(posts).values(postRecords)
  await log(campaignId, 'publisher', 'done', `${postRecords.length} posts scheduled to calendar.`)
  await updateCampaign(campaignId, { currentStep: null, progress: 100, status: 'active', postsCount: postRecords.length })

  return { postsCreated: postRecords.length }
}
